export default {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SET_MOBILE: 'SET_MOBILE',
  SET_DESKTOP: 'SET_DESKTOP',
  SET_BODY_TYPE: 'SET_BODY_TYPE',
  SET_FACE_TYPE: 'SET_FACE_TYPE',
  SET_HEADWEAR_TYPE: 'SET_HEADWEAR_TYPE',
}
