const monsters = [
  {
    id: 1,
    name: 'Monster 1',
    eyes: 'eyes_1',
    mouth: 'mouth_1',
    body: 'body_1',
  },
  {
    id: 2,
    name: 'Monster 2',
    eyes: 'eyes_1',
    mouth: 'mouth_2',
    body: 'body_1',
  },
  {
    id: 3,
    name: 'Monster 3',
    eyes: 'eyes_2',
    mouth: 'mouth_1',
    body: 'body_2',
  },
  {
    id: 4,
    name: 'Monster 4',
    eyes: 'eyes_2',
    mouth: 'mouth_2',
    body: 'body_2',
  },
  {
    id: 5,
    name: 'Monster 4',
    eyes: 'eyes_2',
    mouth: 'mouth_2',
    body: 'body_2',
  },
  {
    id: 6,
    name: 'Monster 4',
    eyes: 'eyes_2',
    mouth: 'mouth_2',
    body: 'body_2',
  },
  {
    id: 7,
    name: 'Monster 4',
    eyes: 'eyes_2',
    mouth: 'mouth_2',
    body: 'body_2',
  },
  {
    id: 8,
    name: 'Monster 4',
    eyes: 'eyes_2',
    mouth: 'mouth_2',
    body: 'body_2',
  },
  {
    id: 9,
    name: 'Monster 4',
    eyes: 'eyes_2',
    mouth: 'mouth_2',
    body: 'body_2',
  },
  {
    id: 10,
    name: 'Monster 4',
    eyes: 'eyes_2',
    mouth: 'mouth_2',
    body: 'body_2',
  },
  {
    id: 11,
    name: 'Monster 4',
    eyes: 'eyes_2',
    mouth: 'mouth_2',
    body: 'body_2',
  },
  {
    id: 12,
    name: 'Monster 4',
    eyes: 'eyes_2',
    mouth: 'mouth_2',
    body: 'body_2',
  },
]

export default monsters
